[build]
builder = "NIXPACKS"
buildCommand = "npm --prefix frontend install && npm --prefix frontend run build && pip install -r backend/requirements.txt"

[deploy]
startCommand = "python backend/app/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
