[build]
builder = "NIXPACKS"
buildCommand = "npm --prefix frontend install && npm --prefix frontend run build && pip install -r backend/requirements.txt"

[deploy]
startCommand = "PYTHONPATH=$PWD python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
